Repository MYAMBO/GLaDOS, pull requests merged in 2025-09, with the labels that each got.

#1 Feature error handling lib
  .gitignore
  ErrorHandling/ErrorHandling.hs
  ErrorHandling/ErrorHandlingDocumentattion.md
  package.yaml
  test/Test.hs
  test/TestErrorHandling.hs
Labels: documentation, enhancement

#2 Feature div
  src/Interpret.hs
  src/Tools.hs
Labels: enhancement

#4 feat(ast): added the ast
  src/Ast/Ast.hs
Labels: enhancement

#8 Feature call
  .gitignore
  ErrorHandling/ErrorHandling.hs
  ErrorHandling/ErrorHandlingDocumentattion.md
  package.yaml
  src/Ast/Ast.hs
  src/DataStored.hs
  src/Interpret.hs
  src/Tools.hs
  test/Test.hs
  test/TestErrorHandling.hs
  test/TestInterpret.hs
Labels: enhancement

#23 Feature jenkins linking
  .github/workflows/haskell_build.yml
  .gitignore
  Makefile
  package.yaml
  test/Test.hs
  test/TestAst.hs
  test/TestInterpret.hs
  test/TestParsing.hs
Labels: tests

#25 fix(Test): use tasty-hspec for coverage
  package.yaml
  test/Test.hs
Labels: fix
